# Uncomment the next line to define a global platform for your project
platform :ios, '10.3'

target 'webAccess' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for webAccess
	pod 'SwiftyJSON', '3.1.4'
	pod 'APIKit', :git => 'https://github.com/ishkawa/APIKit.git', :tag => '3.1.2'
	pod 'Himotoki', :git => 'https://github.com/ikesyo/Himotoki.git', :tag => '3.1.0'

end
