# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ForceUpdate' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ForceUpdate

  pod 'Siren', :git => 'https://github.com/ArtSabintsev/Siren.git', :branch => 'swift3.1'
  
end
